global:
  scrape_interval: 15s

alerting:
  alertmanagers: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: monitor-bot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - monitor-bot:8090
